Added image of python with jira and github libs
KazanExpress/ke-infra-docker pull request #162
Opened 2023-04-12 20:35 UTC by timkabot

This image is needed for CI/CD of android drone

2023-04-13 04:00 UTC, mans0ry requested changes

2023-04-13 04:00 UTC, mans0ry commented on images/android/v3.8-python-jira-git/Dockerfile
> +FROM python:3.8
я бы взял слим бустер, если не критично, он меньше весит + быстрее собираться будет
```suggestion
FROM python:3.8-slim-buster
```

2023-04-13 04:00 UTC, mans0ry commented on images/android/v3.8-python-jira-git/Dockerfile
> +RUN pip install click jira PyGithub
```suggestion
RUN pip install --no-cache-dir click jira PyGithub
```
https://app.deepsource.com/directory/analyzers/docker/issues/DOK-P1003

2023-04-19 06:02 UTC, kuraleb commented on images/android/v3.8-python-jira-git/Dockerfile
> +RUN pip install --no-cache-dir click jira PyGithub
да, похоже на какой-то баг
В другом ПР нет такой проблемы

2023-04-20 06:47 UTC, closed without merging